export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED'

export const GET_NEXT_POSTS_SUCCESS = 'GET_NEXT_POSTS_SUCCESS'
export const GET_NEXT_POSTS_FAILED = 'GET_NEXT_POSTS_FAILED'

export const SUBMIT_POST = 'SUBMIT_POST'
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS'
export const SUBMIT_POST_FAILED = 'SUBMIT_POST_FAILED'

export const GET_COMPLAINTS = 'GET_COMPLAINTS'
export const GET_COMPLAINTS_SUCCESS = 'GET_COMPLAINTS_SUCCESS'
export const GET_COMPLAINTS_FAILED = 'GET_COMPLAINTS_FAILED'

export const CHANGE_COMPLAINT_STATUS = 'CHANGE_COMPLAINT_STATUS' 
export const CHANGE_COMPLAINT_STATUS_SUCCESS = 'CHANGE_COMPLAINT_STATUS_SUCCESS' 
export const CHANGE_COMPLAINT_STATUS_FAILED = 'CHANGE_COMPLAINT_STATUS_FAILED' 

export const SUBMIT_COMPLAINT = 'SUBMIT_COMPLAINT'
export const SUBMIT_COMPLAINT_SUCCESS = 'SUBMIT_COMPLAINT_SUCCESS'
export const SUBMIT_COMPLAINT_FAILED = 'SUBMIT_COMPLAINT_FAILED'

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'

export const SET_AUTH_DATA = 'SET_AUTH_DATA'
export const SET_AUTH_DATA_SUCCESS = 'SET_AUTH_DATA_SUCCESS'
export const SET_AUTH_DATA_FAILED = 'SET_AUTH_DATA_FAILED'

export const LIKE_POST = 'LIKE_POST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAILED = 'LIKE_POST_FAILED'

export const DISLIKE_POST = 'DISLIKE_POST'
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS'
export const DISLIKE_POST_FAILED = 'DISLIKE_POST_FAILED'