export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_NEXT_POSTS_SUCCESS = 'GET_NEXT_POSTS_SUCCESS' 
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED'

export const GET_REQUESTS = 'GET_REQUESTS'
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS'
export const GET_NEXT_REQUESTS_SUCCESS = 'GET_NEXT_REQUESTS_SUCCESS' 
export const GET_REQUESTS_FAILED = 'GET_REQUESTS_FAILED'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED'

export const GET_FORM_CONFIG = 'GET_FORM_CONFIG'
export const GET_FORM_CONFIG_SUCCESS = 'GET_FORM_CONFIG_SUCCESS'
export const GET_FORM_CONFIG_FAILED = 'GET_FORM_CONFIG_FAILED'

export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED'

export const GET_COMPLAINT_IMAGES = 'GET_COMPLAINT_IMAGES'
export const GET_COMPLAINT_IMAGES_SUCCESS = 'GET_COMPLAINT_IMAGES_SUCCESS'
export const GET_COMPLAINT_IMAGES_FAILED = 'GET_COMPLAINT_IMAGES_FAILED'

export const GET_BUZZ_IMAGES = 'GET_BUZZ_IMAGES'
export const GET_BUZZ_IMAGES_SUCCESS = 'GET_BUZZ_IMAGES_SUCCESS'
export const GET_BUZZ_IMAGES_FAILED = 'GET_BUZZ_IMAGES_FAILED'

export const GET_USERS = 'GET_USERS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'

export const GET_CHAT_HISTORY = 'GET_CHAT_HISTORY'
export const GET_CHAT_HISTORY_SUCCESS = 'GET_CHAT_HISTORY_SUCCESS'
export const GET_CHAT_HISTORY_FAILED = 'GET_CHAT_HISTORY_FAILED'

export const SUBMIT_POST = 'SUBMIT_POST'
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS'
export const SUBMIT_POST_FAILED = 'SUBMIT_POST_FAILED'

export const GET_COMPLAINTS = 'GET_COMPLAINTS'
export const GET_COMPLAINTS_SUCCESS = 'GET_COMPLAINTS_SUCCESS'
export const GET_COMPLAINTS_FAILED = 'GET_COMPLAINTS_FAILED'

export const CHANGE_COMPLAINT_STATUS = 'CHANGE_COMPLAINT_STATUS' 
export const CHANGE_COMPLAINT_STATUS_SUCCESS = 'CHANGE_COMPLAINT_STATUS_SUCCESS' 
export const CHANGE_COMPLAINT_STATUS_FAILED = 'CHANGE_COMPLAINT_STATUS_FAILED' 

export const SUBMIT_COMPLAINT = 'SUBMIT_COMPLAINT'
export const SUBMIT_COMPLAINT_SUCCESS = 'SUBMIT_COMPLAINT_SUCCESS'
export const SUBMIT_COMPLAINT_FAILED = 'SUBMIT_COMPLAINT_FAILED'

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'

export const SET_AUTH_DATA = 'SET_AUTH_DATA'
export const SET_AUTH_DATA_SUCCESS = 'SET_AUTH_DATA_SUCCESS'
export const SET_AUTH_DATA_FAILED = 'SET_AUTH_DATA_FAILED'

export const CHANGE_PROFILE_REQUEST_STATUS = 'CHANGE_PROFILE_REQUEST_STATUS'
export const CHANGE_PROFILE_REQUEST_STATUS_SUCCESS = 'CHANGE_PROFILE_REQUEST_STATUS_SUCCESS'
export const CHANGE_PROFILE_REQUEST_STATUS_FAILED = 'CHANGE_PROFILE_REQUEST_STATUS_FAILED'

export const CHANGE_LIKE_DISLIKE = 'CHANGE_LIKE_DISLIKE'
export const CHANGE_LIKE_DISLIKE_FAILED = 'CHANGE_LIKE_DISLIKE_FAILED'
export const CHANGE_LIKE_DISLIKE_SUCCESS = 'CHANGE_LIKE_DISLIKE_SUCCESS'

export const CHANGE_FOLLOW_STATUS = 'CHANGE_FOLLOW_STATUS'
export const CHANGE_FOLLOW_STATUS_FAILED = 'CHANGE_FOLLOW_STATUS_FAILED'
export const CHANGE_FOLLOW_STATUS_SUCCESS = 'CHANGE_FOLLOW_STATUS_SUCCESS'

export const CHANGE_FRIEND_STATUS = 'CHANGE_FOLLOW_STATUS'
export const CHANGE_FRIEND_STATUS_FAILED = 'CHANGE_FRIEND_STATUS_FAILED'
export const CHANGE_FRIEND_STATUS_SUCCESS = 'CHANGE_FRIEND_STATUS_SUCCESS'

export const UPDATE_COMPLAINT = 'UPDATE_COMPLAINT'
export const UPDATE_COMPLAINT_SUCCESS = 'UPDATE_COMPLAINT_SUCCESS'
export const UPDATE_COMPLAINT_FAILED = 'UPDATE_COMPLAINT_FAILED'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED'

export const SOCKET_CONNECTION_ESTABLISHED = 'SOCKET_CONNECTION_ESTABLISHED'
export const SOCKET_CONNECTION_FAILED = 'SOCKET_CONNECTION_FAILED'

export const DELETE_CHAT = 'DELETE_CHAT' 
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS' 
export const DELETE_CHAT_FAILED = 'DELETE_CHAT_FAILED' 